apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create"]

- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hlf-fabric-management-binding-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: hlf-fabric-management
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaincode-deployment-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaincode-deployment-manager-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: chaincode-deployment-manager
  apiGroup: rbac.authorization.k8s.io
