channels:
  firstchannel:
    orderers:
    - orderer1-org1
    - orderer2-org1
    - orderer3-org1
    peers:
      peer1-org1:
        chaincodequery: true
        endorsingpeer: true
        ledgerquery: true
client:
  bccsp:
    security:
      default:
        provider: SW
      enabled: true
      ephemeral: false
      hashalgorithm: SHA2
      level: 256
      softverify: true
  eventservice:
    timeout:
      connection: 120s
      registrationresponse: 120s
  logging:
    level: info
  orderer:
    timeout:
      connection: 120s
      response: 120s
  organization: org1
  peer:
    timeout:
      connection: 120s
      executetxresponse: 120s
      queryresponse: 120s
  tlscerts:
    client:
      cert:
        pem: |
          -----BEGIN CERTIFICATE-----
          MIICJDCCAcmgAwIBAgIRAKgoq44SkiTQjhUG7aRCl8owCgYIKoZIzj0EAwIwgZox
          CzAJBgNVBAYTAlVTMQswCQYDVQQIEwJWQTEPMA0GA1UEBxMGVmllbm5hMSkwJwYD
          VQQJEyA4NjE4IFdlc3R3b29kIENlbnRlciBEciwgU1RFIDMxMDEOMAwGA1UEERMF
          MjIxODIxFDASBgNVBAoTC0NvcnNoYSwgSW5jMQ0wCwYDVQQLEwRvcmcxMQ0wCwYD
          VQQDEwRpY2EwMB4XDTI1MDgyNTE0MDMzNloXDTI1MTEyMzE0MDMzNlowSDEPMA0G
          A1UECxMGY2xpZW50MTUwMwYDVQQDEyxBdVYwZVcxemdxTzVuYWhmbGpqcU1LWlVR
          RGJDUWNuV042SnY1a29aNHd4NzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGxO
          /p70ovC27bvMetDugEkdq2Wr0Vz4o9lmA7z4EVCJi0ArVNov0NanJ3YvA3WyExSo
          bI4n+HwdxbPxYN6hKsWjQTA/MA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAA
          MB8GA1UdIwQYMBaAFFAwbPwFhFCdM7BVpLwxAN7wzmRrMAoGCCqGSM49BAMCA0kA
          MEYCIQDNU5JspX0E862cEluytfDJCQqUd6A77t3a69+9kcdEDgIhAOn3F8iGTH2X
          RCw8ms4Sjoe8FOFfOsnPJe5fI1sF1YRG
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIICijCCAjGgAwIBAgIBATAKBggqhkjOPQQDAjCBmjELMAkGA1UEBhMCVVMxCzAJ
          BgNVBAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdv
          b2QgQ2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChML
          Q29yc2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBHJjYTAwHhcNMjEw
          ODEzMDY0NjQzWhcNMzEwODEzMTY0NjQzWjCBmjELMAkGA1UEBhMCVVMxCzAJBgNV
          BAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdvb2Qg
          Q2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChMLQ29y
          c2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBGljYTAwWTATBgcqhkjO
          PQIBBggqhkjOPQMBBwNCAASgFAHQ5I98AxBuMtcHIgLgnwF9XbjFKKCKWf07argx
          OQJ9yMliKv6E/3MdVZGSaosqiSRG7mrLMfb81ja8PeMpo2YwZDAOBgNVHQ8BAf8E
          BAMCAgQwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUUDBs/AWEUJ0zsFWk
          vDEA3vDOZGswHwYDVR0jBBgwFoAUO+UBUJ1a2qyeEKA1cB4XQE6Lwg8wCgYIKoZI
          zj0EAwIDRwAwRAIgcClNC7BYdgK9Qu2zN+wBx+tFw9gMtztjJS0eWIdwIzcCIGbD
          ER4SWXNYEG7UcA2XkZKn9x4MI3k5pAxLwFPNgRoW
          -----END CERTIFICATE-----
      key:
        pem: |
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIHVvXb1pwO778A6M6m49WQoVgNiWlS4FlDI24G6naH8poAoGCCqGSM49
          AwEHoUQDQgAEbE7+nvSi8Lbtu8x60O6ASR2rZavRXPij2WYDvPgRUImLQCtU2i/Q
          1qcndi8DdbITFKhsjif4fB3Fs/Fg3qEqxQ==
          -----END EC PRIVATE KEY-----
    systemcertpool: false
description: 'Corsha Fabric Network, prefix: cal-dln'
name: corsha-fabric-network
orderers:
  orderer1-org1:
    grpcoptions:
      allow-insecure: false
    tlscacerts:
      path: ""
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICijCCAjGgAwIBAgIBATAKBggqhkjOPQQDAjCBmjELMAkGA1UEBhMCVVMxCzAJ
        BgNVBAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdv
        b2QgQ2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChML
        Q29yc2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBHJjYTAwHhcNMjEw
        ODEzMDY0NjQzWhcNMzEwODEzMTY0NjQzWjCBmjELMAkGA1UEBhMCVVMxCzAJBgNV
        BAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdvb2Qg
        Q2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChMLQ29y
        c2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBGljYTAwWTATBgcqhkjO
        PQIBBggqhkjOPQMBBwNCAASgFAHQ5I98AxBuMtcHIgLgnwF9XbjFKKCKWf07argx
        OQJ9yMliKv6E/3MdVZGSaosqiSRG7mrLMfb81ja8PeMpo2YwZDAOBgNVHQ8BAf8E
        BAMCAgQwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUUDBs/AWEUJ0zsFWk
        vDEA3vDOZGswHwYDVR0jBBgwFoAUO+UBUJ1a2qyeEKA1cB4XQE6Lwg8wCgYIKoZI
        zj0EAwIDRwAwRAIgcClNC7BYdgK9Qu2zN+wBx+tFw9gMtztjJS0eWIdwIzcCIGbD
        ER4SWXNYEG7UcA2XkZKn9x4MI3k5pAxLwFPNgRoW
        -----END CERTIFICATE-----
    url: grpcs://orderer1-org1.cal-dln.svc.cluster.local:7050
  orderer2-org1:
    grpcoptions:
      allow-insecure: false
    tlscacerts:
      path: ""
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICijCCAjGgAwIBAgIBATAKBggqhkjOPQQDAjCBmjELMAkGA1UEBhMCVVMxCzAJ
        BgNVBAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdv
        b2QgQ2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChML
        Q29yc2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBHJjYTAwHhcNMjEw
        ODEzMDY0NjQzWhcNMzEwODEzMTY0NjQzWjCBmjELMAkGA1UEBhMCVVMxCzAJBgNV
        BAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdvb2Qg
        Q2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChMLQ29y
        c2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBGljYTAwWTATBgcqhkjO
        PQIBBggqhkjOPQMBBwNCAASgFAHQ5I98AxBuMtcHIgLgnwF9XbjFKKCKWf07argx
        OQJ9yMliKv6E/3MdVZGSaosqiSRG7mrLMfb81ja8PeMpo2YwZDAOBgNVHQ8BAf8E
        BAMCAgQwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUUDBs/AWEUJ0zsFWk
        vDEA3vDOZGswHwYDVR0jBBgwFoAUO+UBUJ1a2qyeEKA1cB4XQE6Lwg8wCgYIKoZI
        zj0EAwIDRwAwRAIgcClNC7BYdgK9Qu2zN+wBx+tFw9gMtztjJS0eWIdwIzcCIGbD
        ER4SWXNYEG7UcA2XkZKn9x4MI3k5pAxLwFPNgRoW
        -----END CERTIFICATE-----
    url: grpcs://orderer2-org1.cal-dln.svc.cluster.local:7050
  orderer3-org1:
    grpcoptions:
      allow-insecure: false
    tlscacerts:
      path: ""
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICijCCAjGgAwIBAgIBATAKBggqhkjOPQQDAjCBmjELMAkGA1UEBhMCVVMxCzAJ
        BgNVBAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdv
        b2QgQ2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChML
        Q29yc2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBHJjYTAwHhcNMjEw
        ODEzMDY0NjQzWhcNMzEwODEzMTY0NjQzWjCBmjELMAkGA1UEBhMCVVMxCzAJBgNV
        BAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdvb2Qg
        Q2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChMLQ29y
        c2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBGljYTAwWTATBgcqhkjO
        PQIBBggqhkjOPQMBBwNCAASgFAHQ5I98AxBuMtcHIgLgnwF9XbjFKKCKWf07argx
        OQJ9yMliKv6E/3MdVZGSaosqiSRG7mrLMfb81ja8PeMpo2YwZDAOBgNVHQ8BAf8E
        BAMCAgQwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUUDBs/AWEUJ0zsFWk
        vDEA3vDOZGswHwYDVR0jBBgwFoAUO+UBUJ1a2qyeEKA1cB4XQE6Lwg8wCgYIKoZI
        zj0EAwIDRwAwRAIgcClNC7BYdgK9Qu2zN+wBx+tFw9gMtztjJS0eWIdwIzcCIGbD
        ER4SWXNYEG7UcA2XkZKn9x4MI3k5pAxLwFPNgRoW
        -----END CERTIFICATE-----
    url: grpcs://orderer3-org1.cal-dln.svc.cluster.local:7050
organizations:
  org0:
    cryptopath: msp
    mspid: org0
    peers:
    - peer1-org0
    users:
      auv0ew1zgqo5nahfljjqmkzuqdbcqcnwn6jv5koz4wx7:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICJDCCAcmgAwIBAgIRAKgoq44SkiTQjhUG7aRCl8owCgYIKoZIzj0EAwIwgZox
            CzAJBgNVBAYTAlVTMQswCQYDVQQIEwJWQTEPMA0GA1UEBxMGVmllbm5hMSkwJwYD
            VQQJEyA4NjE4IFdlc3R3b29kIENlbnRlciBEciwgU1RFIDMxMDEOMAwGA1UEERMF
            MjIxODIxFDASBgNVBAoTC0NvcnNoYSwgSW5jMQ0wCwYDVQQLEwRvcmcxMQ0wCwYD
            VQQDEwRpY2EwMB4XDTI1MDgyNTE0MDMzNloXDTI1MTEyMzE0MDMzNlowSDEPMA0G
            A1UECxMGY2xpZW50MTUwMwYDVQQDEyxBdVYwZVcxemdxTzVuYWhmbGpqcU1LWlVR
            RGJDUWNuV042SnY1a29aNHd4NzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGxO
            /p70ovC27bvMetDugEkdq2Wr0Vz4o9lmA7z4EVCJi0ArVNov0NanJ3YvA3WyExSo
            bI4n+HwdxbPxYN6hKsWjQTA/MA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAA
            MB8GA1UdIwQYMBaAFFAwbPwFhFCdM7BVpLwxAN7wzmRrMAoGCCqGSM49BAMCA0kA
            MEYCIQDNU5JspX0E862cEluytfDJCQqUd6A77t3a69+9kcdEDgIhAOn3F8iGTH2X
            RCw8ms4Sjoe8FOFfOsnPJe5fI1sF1YRG
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            MIICijCCAjGgAwIBAgIBATAKBggqhkjOPQQDAjCBmjELMAkGA1UEBhMCVVMxCzAJ
            BgNVBAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdv
            b2QgQ2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChML
            Q29yc2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBHJjYTAwHhcNMjEw
            ODEzMDY0NjQzWhcNMzEwODEzMTY0NjQzWjCBmjELMAkGA1UEBhMCVVMxCzAJBgNV
            BAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdvb2Qg
            Q2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChMLQ29y
            c2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBGljYTAwWTATBgcqhkjO
            PQIBBggqhkjOPQMBBwNCAASgFAHQ5I98AxBuMtcHIgLgnwF9XbjFKKCKWf07argx
            OQJ9yMliKv6E/3MdVZGSaosqiSRG7mrLMfb81ja8PeMpo2YwZDAOBgNVHQ8BAf8E
            BAMCAgQwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUUDBs/AWEUJ0zsFWk
            vDEA3vDOZGswHwYDVR0jBBgwFoAUO+UBUJ1a2qyeEKA1cB4XQE6Lwg8wCgYIKoZI
            zj0EAwIDRwAwRAIgcClNC7BYdgK9Qu2zN+wBx+tFw9gMtztjJS0eWIdwIzcCIGbD
            ER4SWXNYEG7UcA2XkZKn9x4MI3k5pAxLwFPNgRoW
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIHVvXb1pwO778A6M6m49WQoVgNiWlS4FlDI24G6naH8poAoGCCqGSM49
            AwEHoUQDQgAEbE7+nvSi8Lbtu8x60O6ASR2rZavRXPij2WYDvPgRUImLQCtU2i/Q
            1qcndi8DdbITFKhsjif4fB3Fs/Fg3qEqxQ==
            -----END EC PRIVATE KEY-----
  org1:
    cryptopath: msp
    mspid: org1
    peers:
    - peer1-org1
    users:
      auv0ew1zgqo5nahfljjqmkzuqdbcqcnwn6jv5koz4wx7:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICJDCCAcmgAwIBAgIRAKgoq44SkiTQjhUG7aRCl8owCgYIKoZIzj0EAwIwgZox
            CzAJBgNVBAYTAlVTMQswCQYDVQQIEwJWQTEPMA0GA1UEBxMGVmllbm5hMSkwJwYD
            VQQJEyA4NjE4IFdlc3R3b29kIENlbnRlciBEciwgU1RFIDMxMDEOMAwGA1UEERMF
            MjIxODIxFDASBgNVBAoTC0NvcnNoYSwgSW5jMQ0wCwYDVQQLEwRvcmcxMQ0wCwYD
            VQQDEwRpY2EwMB4XDTI1MDgyNTE0MDMzNloXDTI1MTEyMzE0MDMzNlowSDEPMA0G
            A1UECxMGY2xpZW50MTUwMwYDVQQDEyxBdVYwZVcxemdxTzVuYWhmbGpqcU1LWlVR
            RGJDUWNuV042SnY1a29aNHd4NzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGxO
            /p70ovC27bvMetDugEkdq2Wr0Vz4o9lmA7z4EVCJi0ArVNov0NanJ3YvA3WyExSo
            bI4n+HwdxbPxYN6hKsWjQTA/MA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAA
            MB8GA1UdIwQYMBaAFFAwbPwFhFCdM7BVpLwxAN7wzmRrMAoGCCqGSM49BAMCA0kA
            MEYCIQDNU5JspX0E862cEluytfDJCQqUd6A77t3a69+9kcdEDgIhAOn3F8iGTH2X
            RCw8ms4Sjoe8FOFfOsnPJe5fI1sF1YRG
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            MIICijCCAjGgAwIBAgIBATAKBggqhkjOPQQDAjCBmjELMAkGA1UEBhMCVVMxCzAJ
            BgNVBAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdv
            b2QgQ2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChML
            Q29yc2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBHJjYTAwHhcNMjEw
            ODEzMDY0NjQzWhcNMzEwODEzMTY0NjQzWjCBmjELMAkGA1UEBhMCVVMxCzAJBgNV
            BAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdvb2Qg
            Q2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChMLQ29y
            c2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBGljYTAwWTATBgcqhkjO
            PQIBBggqhkjOPQMBBwNCAASgFAHQ5I98AxBuMtcHIgLgnwF9XbjFKKCKWf07argx
            OQJ9yMliKv6E/3MdVZGSaosqiSRG7mrLMfb81ja8PeMpo2YwZDAOBgNVHQ8BAf8E
            BAMCAgQwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUUDBs/AWEUJ0zsFWk
            vDEA3vDOZGswHwYDVR0jBBgwFoAUO+UBUJ1a2qyeEKA1cB4XQE6Lwg8wCgYIKoZI
            zj0EAwIDRwAwRAIgcClNC7BYdgK9Qu2zN+wBx+tFw9gMtztjJS0eWIdwIzcCIGbD
            ER4SWXNYEG7UcA2XkZKn9x4MI3k5pAxLwFPNgRoW
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIHVvXb1pwO778A6M6m49WQoVgNiWlS4FlDI24G6naH8poAoGCCqGSM49
            AwEHoUQDQgAEbE7+nvSi8Lbtu8x60O6ASR2rZavRXPij2WYDvPgRUImLQCtU2i/Q
            1qcndi8DdbITFKhsjif4fB3Fs/Fg3qEqxQ==
            -----END EC PRIVATE KEY-----
  org2:
    cryptopath: msp
    mspid: org2
    peers:
    - peer1-org2
    users:
      auv0ew1zgqo5nahfljjqmkzuqdbcqcnwn6jv5koz4wx7:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICJDCCAcmgAwIBAgIRAKgoq44SkiTQjhUG7aRCl8owCgYIKoZIzj0EAwIwgZox
            CzAJBgNVBAYTAlVTMQswCQYDVQQIEwJWQTEPMA0GA1UEBxMGVmllbm5hMSkwJwYD
            VQQJEyA4NjE4IFdlc3R3b29kIENlbnRlciBEciwgU1RFIDMxMDEOMAwGA1UEERMF
            MjIxODIxFDASBgNVBAoTC0NvcnNoYSwgSW5jMQ0wCwYDVQQLEwRvcmcxMQ0wCwYD
            VQQDEwRpY2EwMB4XDTI1MDgyNTE0MDMzNloXDTI1MTEyMzE0MDMzNlowSDEPMA0G
            A1UECxMGY2xpZW50MTUwMwYDVQQDEyxBdVYwZVcxemdxTzVuYWhmbGpqcU1LWlVR
            RGJDUWNuV042SnY1a29aNHd4NzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGxO
            /p70ovC27bvMetDugEkdq2Wr0Vz4o9lmA7z4EVCJi0ArVNov0NanJ3YvA3WyExSo
            bI4n+HwdxbPxYN6hKsWjQTA/MA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAA
            MB8GA1UdIwQYMBaAFFAwbPwFhFCdM7BVpLwxAN7wzmRrMAoGCCqGSM49BAMCA0kA
            MEYCIQDNU5JspX0E862cEluytfDJCQqUd6A77t3a69+9kcdEDgIhAOn3F8iGTH2X
            RCw8ms4Sjoe8FOFfOsnPJe5fI1sF1YRG
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            MIICijCCAjGgAwIBAgIBATAKBggqhkjOPQQDAjCBmjELMAkGA1UEBhMCVVMxCzAJ
            BgNVBAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdv
            b2QgQ2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChML
            Q29yc2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBHJjYTAwHhcNMjEw
            ODEzMDY0NjQzWhcNMzEwODEzMTY0NjQzWjCBmjELMAkGA1UEBhMCVVMxCzAJBgNV
            BAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdvb2Qg
            Q2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChMLQ29y
            c2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBGljYTAwWTATBgcqhkjO
            PQIBBggqhkjOPQMBBwNCAASgFAHQ5I98AxBuMtcHIgLgnwF9XbjFKKCKWf07argx
            OQJ9yMliKv6E/3MdVZGSaosqiSRG7mrLMfb81ja8PeMpo2YwZDAOBgNVHQ8BAf8E
            BAMCAgQwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUUDBs/AWEUJ0zsFWk
            vDEA3vDOZGswHwYDVR0jBBgwFoAUO+UBUJ1a2qyeEKA1cB4XQE6Lwg8wCgYIKoZI
            zj0EAwIDRwAwRAIgcClNC7BYdgK9Qu2zN+wBx+tFw9gMtztjJS0eWIdwIzcCIGbD
            ER4SWXNYEG7UcA2XkZKn9x4MI3k5pAxLwFPNgRoW
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIHVvXb1pwO778A6M6m49WQoVgNiWlS4FlDI24G6naH8poAoGCCqGSM49
            AwEHoUQDQgAEbE7+nvSi8Lbtu8x60O6ASR2rZavRXPij2WYDvPgRUImLQCtU2i/Q
            1qcndi8DdbITFKhsjif4fB3Fs/Fg3qEqxQ==
            -----END EC PRIVATE KEY-----
peers:
  peer1-org1:
    eventurl: grpcs://peer1-org1.cal-dln.svc.cluster.local:7051
    grpcoptions:
      allow-insecure: false
      keep-alive-time: 5m
    tlscacerts:
      path: ""
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICijCCAjGgAwIBAgIBATAKBggqhkjOPQQDAjCBmjELMAkGA1UEBhMCVVMxCzAJ
        BgNVBAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdv
        b2QgQ2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChML
        Q29yc2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBHJjYTAwHhcNMjEw
        ODEzMDY0NjQzWhcNMzEwODEzMTY0NjQzWjCBmjELMAkGA1UEBhMCVVMxCzAJBgNV
        BAgTAlZBMQ8wDQYDVQQHEwZWaWVubmExKTAnBgNVBAkTIDg2MTggV2VzdHdvb2Qg
        Q2VudGVyIERyLCBTVEUgMzEwMQ4wDAYDVQQREwUyMjE4MjEUMBIGA1UEChMLQ29y
        c2hhLCBJbmMxDTALBgNVBAsTBG9yZzExDTALBgNVBAMTBGljYTAwWTATBgcqhkjO
        PQIBBggqhkjOPQMBBwNCAASgFAHQ5I98AxBuMtcHIgLgnwF9XbjFKKCKWf07argx
        OQJ9yMliKv6E/3MdVZGSaosqiSRG7mrLMfb81ja8PeMpo2YwZDAOBgNVHQ8BAf8E
        BAMCAgQwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUUDBs/AWEUJ0zsFWk
        vDEA3vDOZGswHwYDVR0jBBgwFoAUO+UBUJ1a2qyeEKA1cB4XQE6Lwg8wCgYIKoZI
        zj0EAwIDRwAwRAIgcClNC7BYdgK9Qu2zN+wBx+tFw9gMtztjJS0eWIdwIzcCIGbD
        ER4SWXNYEG7UcA2XkZKn9x4MI3k5pAxLwFPNgRoW
        -----END CERTIFICATE-----
    url: grpcs://peer1-org1.cal-dln.svc.cluster.local:7051
version: 1.0.0
x-type: hlfv1
