# Copyright Corsha Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Default values for simi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# True if bench-consumer and rabbitmq should be deployed
isBenchmark: true

# True if a simi failure means the job should fail
shouldFailOnError: false

numWorkers: 1
numWriters: 1

operationPeriod: 5s

targetNamespace: staging

uniqueId: default

dataSizeBytes: 32KB

dlnNamespace: changeme

kubectlImage: "docker.io/bitnami/kubectl:latest"

image:
  repository: "corsha/simi-robot"
  tag: "latest"
  consumer:
    repository: "corsha/simi-consumer"
  waiter:
    repository: redhat/ubi8-minimal
    tag: "8.10"
  publisher:
    repository: us-central1-docker.pkg.dev/corsha-tf-gcp-dev-d9bef0/corsha/ironbank/bitnami/kubectl
    tag: 1.30.6

enableTracing: true

resources:
  consumer:
    requests:
      cpu: 100m
      memory: 64Mi
  simi:
    limits:
      cpu: 100m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
rabbitmq:
  extraEnvVars:
    - name: RABBITMQ_DEFAULT_USER
      value: "rabbit"
    - name: RABBITMQ_DEFAULT_PASS
      value: "devRabbit2"
  image:
    registry: docker.io
    repository: library/rabbitmq
    tag: 3.13-management
  persistence:
    enabled: false
  fullnameOverride: rabbitmq
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    ports:
      manager: 15672
  auth:
    password: devRabbit2
    username: rabbit
influxdb:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  fullnameOverride: influx-simi
  image:
    repository: influxdb
    tag: 2.7.12
  auth:
    admin:
      bucket: stats
      org: simi
      password: mysecretpassword
      token: mysecrettoken
  adminUser:
    organization: "simi"
    bucket: "stats"
    user: "admin"
    retention_policy: "0s"
    ## Leave empty to generate a random password and token.
    ## Or fill any of these values to use fixed values.
    password: "mysecretpassword"
    token: "mysecrettoken"
  service:
    port: 8086
  influxdb:
    service:
      ports:
        http: 8086
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
  persistence:
    enabled: false


operationConfig:
  org: Org1MSP
  chaincodeID: "mycc"
  logLevel: INFO
