---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hlf-fabric-management
rules:
  - apiGroups: ["hlf.kungfusoftware.es"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
