# Copyright Corsha Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: simi-config
type: Opaque
stringData:
  simi.yaml: |-
    registerDelay: 5s

    benchmark:
      operationsPerStream: {{ .Values.operationsPerStream }}
      operationPeriod: {{ .Values.operationPeriod }}
      operationType: {{ .Values.operationType }}
    {{- if .Values.isBenchmark }}
      influxConfig:
        url: http://{{ .Values.influxdb.fullnameOverride }}:{{ .Values.influxdb.influxdb.service.ports.http }}
        bucket: {{ .Values.influxdb.auth.admin.bucket }}
      resultSink:
        brokerUrl: amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Values.rabbitmq.fullnameOverride  }}:{{ .Values.rabbitmq.service.port }}/
    {{- end }}

    operationConfig:
    {{- toYaml .Values.operationConfig | nindent 6 }}

{{- if .Values.isBenchmark }}
---
apiVersion: v1
kind: Secret
metadata:
  name: consumer-config
type: Opaque
stringData:
  bench-consumer.yaml: |-
    numWorkers: {{ .Values.numWorkers }}
    operationsPerStream: {{ .Values.operationsPerStream }}
    operationPeriod: {{ .Values.operationPeriod }}
    operationType: {{ .Values.operationType }}
    resultSink:
      brokerUrl: amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Values.rabbitmq.fullnameOverride  }}:{{ .Values.rabbitmq.service.port }}/
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fabric-config
type: Opaque
stringData:
  fabric-config.yaml: |-
{{ .Files.Get "fabric-config.yaml" | indent 4 }}
