// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	metrics "github.com/corshatech/fabric-chaincode/chaincode/internal/chaincode/metrics"
	mock "github.com/stretchr/testify/mock"

	stream "github.com/corshatech/corsha-common/stream"

	uuid "github.com/google/uuid"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// IncrementClientStreamCount provides a mock function with given fields: labels
func (_m *Manager) IncrementClientStreamCount(labels *metrics.LicenseLabels) {
	_m.Called(labels)
}

// IncrementInvalidLicensingEventCount provides a mock function with given fields: labels, cause
func (_m *Manager) IncrementInvalidLicensingEventCount(labels *metrics.LicenseLabels, cause metrics.InvalidLicenseCause) {
	_m.Called(labels, cause)
}

// OnFailedStreamChallenge provides a mock function with given fields: accountID, streamID
func (_m *Manager) OnFailedStreamChallenge(accountID uuid.UUID, streamID stream.ID) {
	_m.Called(accountID, streamID)
}

// RecordChaincodeActionInvocation provides a mock function with given fields: labels
func (_m *Manager) RecordChaincodeActionInvocation(labels *metrics.ActionLabels) {
	_m.Called(labels)
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
