# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  lint-build-test:
    name: Lint Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'

      - name: Install helm
        run: |
          curl -sfL https://raw.githubusercontent.com/helm/helm/master/scripts/get | DESIRED_VERSION='v3.17.0' bash -x

      - name: Install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.61.0

      - name: Lint Go
        run: golangci-lint run --timeout 2m

      - name: Build Simi
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/simi cmd/simi.go
          GOOS=linux GOARCH=amd64 go build -o benchmark/bench-consumer benchmark/cmd/consumer.go

      - name: Test
        run: GO111MODULE=on go test -race -v -coverprofile=coverage.out ./...

      - name: Lint Helm
        run: helm lint k8s/helm/simi --values k8s/helm/simi/ci/ci-values.yaml -f k8s/helm/simi/values.yaml
